### ISSUE TITLE
Cannot start on Linux

### ISSUE THREAD

**Issue by jack9603301** [andrewhodel/grblweb#37]
Cannot start on Linux，The following errors are reported

```
Got error: connect ECONNREFUSED 127.0.0.1:8080 not enabling webcam
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Error: Input/output error setting custom baud rate of 115200
Emitted 'error' event on SerialPort instance at:
    at SerialPort._error (/home/cnc/grblweb/node_modules/@serialport/stream/lib/index.js:200:10)
    at /home/cnc/grblweb/node_modules/@serialport/stream/lib/index.js:242:12

Node.js v17.4.0

```

**Comment by andrewhodel** [comment]
That means your serial port is not working.
